### ISSUE TITLE
Auto start does not work. Need to restart manually after Home Assistant reboot

### ISSUE THREAD

**Issue by mrwee** [adamoutler/HassOSArgonOneAddon#10]
Running version 21 on core-2021.5.3, and "Start on boot" is enabled. However I need to manually restart it before the fan speed is shown / entity is updated. Has been like that on previous versions as well.

**Comment by adamoutler** [comment]
It's set to start far later than other add-ons. It has to communicate with Home Assistant so it is set up as an application and not a service.  Give it a couple of minutes. It will start when the system tells it to start.

**Comment by mrwee** [comment]
That doesn't seem to work for me. After last reboot it's been updating with temperature for 8 hours, but the entity does not work until I manually restart the add-on

**Comment by adamoutler** [comment]
Are you running at temperatures that can use the active cooling?

**Comment by mrwee** [comment]
No, it's 49 degrees C, Low range is set to 55.
When manually restarting it, the log outputs:

`
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: ArgonOne Active Cooling
 Actively keeping your Argon One cool.
-----------------------------------------------------------
 Add-on version: 21
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.13  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2021.5.4
 Home Assistant Supervisor: 2021.04.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Detecting Layout of i2c, we expect to see "1a" here.
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- 1a -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
Settings initialized. Argon One Detected. Beginning monitor..
Current Temperature 49 °C
Level 1 - Fan 0% (OFF)
`

**Comment by adamoutler** [comment]
Can you get a log from a reboot, after it starts?  I have not been able to
reproduce.

**Comment by mrwee** [comment]
Sure. All the log shows is:
```
Current Temperature 47 °C
Current Temperature 47 °C
Current Temperature 47 °C
Current Temperature 49 °C
Current Temperature 48 °C
Current Temperature 48 °C
```

It keeps going, until I manually restart it. Then it works.

**Comment by adamoutler** [comment]
What about the start of the log?

**Comment by mrwee** [comment]
There isn't any. Only similar entries from before the reboot

**Comment by mrwee** [comment]
Just tried setting "low" treshold to 30 degrees, to force the fan on. Still the entity doesn't work and logfile shows current temperature only. Restarting add-on, gives me:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: ArgonOne Active Cooling
 Actively keeping your Argon One cool.
-----------------------------------------------------------
 Add-on version: 21
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.13  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2021.5.4
 Home Assistant Supervisor: 2021.04.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Detecting Layout of i2c, we expect to see "1a" here.
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- 1a -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
Settings initialized. Argon One Detected. Beginning monitor..
Current Temperature 43 °C
Level 2 - Fan 1% (Quiet Low)```

**Comment by adamoutler** [comment]
But restarting the addon makes it work, so that log doesn't help.  Can you get the log on reboot please?

**Comment by mrwee** [comment]
The add-on log contains nothing else than <x> amount of "Current Temperature", before I manually restart it, so there's not much additional I can add.

**Comment by adamoutler** [comment]
This is what I've been asking for.  Please restart and get the log from
startup when you're having the problem.

**Comment by mrwee** [comment]
Not sure I understand why, but here it is:
``Current Temperature 39 °C
Current Temperature 40 °C
Current Temperature 41 °C
Current Temperature 42 °C
Current Temperature 42 °C
Current Temperature 41 °C
Current Temperature 41 °C
Current Temperature 41 °C
Current Temperature 42 °C
Current Temperature 41 °C
Current Temperature 41 °C
Current Temperature 41 °C
Current Temperature 41 °C
Current Temperature 42 °C
Current Temperature 41 °C
Current Temperature 42 °C
Current Temperature 41 °C
Current Temperature 41 °C
Current Temperature 41 °C
Current Temperature 41 °C
Current Temperature 42 °C
Current Temperature 41 °C
Current Temperature 41 °C
Current Temperature 41 °C
Current Temperature 41 °C
Current Temperature 41 °C
Current Temperature 41 °C
Current Temperature 41 °C
Current Temperature 40 °C
Current Temperature 41 °C
Current Temperature 41 °C
Current Temperature 41 °C
Current Temperature 41 °C
Current Temperature 40 °C
Current Temperature 41 °C
Current Temperature 42 °C
Current Temperature 40 °C
Current Temperature 42 °C
Current Temperature 41 °C
Current Temperature 42 °C
Current Temperature 41 °C
Current Temperature 40 °C
Current Temperature 41 °C
Current Temperature 40 °C
Current Temperature 41 °C
Current Temperature 41 °C
Current Temperature 41 °C
Current Temperature 41 °C
Current Temperature 40 °C
Current Temperature 40 °C
Current Temperature 41 °C
Current Temperature 42 °C
Current Temperature 41 °C
Current Temperature 42 °C
Current Temperature 41 °C
Current Temperature 41 °C
Current Temperature 41 °C
Current Temperature 42 °C
Current Temperature 42 °C
Current Temperature 40 °C
Current Temperature 41 °C
Current Temperature 43 °C
Current Temperature 41 °C
Current Temperature 42 °C
Current Temperature 41 °C
Current Temperature 41 °C
Current Temperature 42 °C
Current Temperature 41 °C
Current Temperature 41 °C
Current Temperature 41 °C
Current Temperature 42 °C
Current Temperature 42 °C
Current Temperature 41 °C
Current Temperature 41 °C
Current Temperature 42 °C
Current Temperature 39 °C
Current Temperature 41 °C
Current Temperature 41 °C
Current Temperature 41 °C
Current Temperature 41 °C
Current Temperature 41 °C
Current Temperature 42 °C
Current Temperature 41 °C
Current Temperature 41 °C
Current Temperature 41 °C
Current Temperature 41 °C
Current Temperature 41 °C
Current Temperature 42 °C
Current Temperature 42 °C
Current Temperature 42 °C
Current Temperature 41 °C
Current Temperature 41 °C
Current Temperature 41 °C
Current Temperature 42 °C
Current Temperature 41 °C
Current Temperature 43 °C
Current Temperature 41 °C
Current Temperature 41 °C
Current Temperature 42 °C
Current Temperature 42 °C

**Comment by adamoutler** [comment]
That is not the log after restart.  Please restart and then get the log.

**Comment by adamoutler** [comment]
I'd also like a screenshot of the missing sensor.

**Comment by mrwee** [comment]
I'm sorry, but that's all the add-on contains. Do you mean the Hass log?
Screenshot before / after add-on restart:
Before:
![image](https://user-images.githubusercontent.com/6720774/118600640-901f5900-b7b1-11eb-909f-0756cf907707.png)

After:
![image](https://user-images.githubusercontent.com/6720774/118600667-9a415780-b7b1-11eb-81bb-870f13294fc8.png)

**Comment by adamoutler** [comment]
What you're showing me is a picture of a sensor that has been inactive for a few hours.  I'm asking for you to reboot and send me the app log and a picture of the sensor.

**Comment by mrwee** [comment]
The first screenshot was taken as soon as Hass was rebooted and ready again (< 60 seconds).
The sensor stays this way until add-on restart. There is no additional log entries besides "Current temperature" entries until I manually restart the add-on. It simply seems like the add-on doesn't start properly after a Hass reboot.

But I just tried something else. Rebooting the entire host, makes the add-on work at reboot. If I just restart Home Assistant, then it doesn't start correctly, thus only shows "Current temperature" in the log.

**Comment by adamoutler** [comment]
This is expected behavior. There is no addon.  If you see it is disabled, then the sensor isn't changing.  If the sensor isn't changing then there is no way for Home Assistant to verify the sensor is there.  Try setting your limits near the CPU temperature so that it kicks on once in a while.

**Comment by Mariusthvdb** [comment]
noticed that too https://community.home-assistant.io/t/argon-one-active-cooling-addon/262598/242
though manually restarting the add-on (apparently it is running, showing Stop, Restart, Uninstall) after that does show the sensor. 

Tbh, this is not really expected behavior from a user pov. Could some kind of guard be implemented? already have the thresholds near the most frequent measured temp.
