### ISSUE TITLE
deactivate the console output

### ISSUE THREAD

**Issue by corgan2222** [adamoutler/HassOSArgonOneAddon#11]
The Addon works fine, but is there a way to deactivate the syslog spam from this addon on each temperature change??
tnxs!

**Comment by adamoutler** [comment]
By which method are you observing it?

**Comment by corgan2222** [comment]
Running a Raspbian GNU/Linux 10 (buster) on a RP4 with manual HA installation.
ArgonOne is installed as a supervisor add-on.

There are some other non HA related things running on the pi, that for I'm forwarding the syslog to a central syslog server.

**Comment by corgan2222** [comment]
any new about this? :)

**Comment by adamoutler** [comment]
I will have to set up a test to check this maybe this weekend or next.  A log would be helpful so I can at least see the messages.  

Keep in mind,  This was designed for HAOS where there are no good options. This may not be fixable.

**Comment by corgan2222** [comment]
![grafik](https://user-images.githubusercontent.com/12233951/119445509-3973cb00-bd2d-11eb-8079-0feca8860a2a.png)

does this help you in any way?

i thinks its this line here
https://github.com/adamoutler/HassOSArgonOneAddon/blob/f8f6b9045cc6d6ec4f4f6374cca06831eff10721/argonOne/run.sh#L130

maybe you want to ad a config variable for debug.

**Comment by adamoutler** [comment]
Fixed in version 22

**Comment by corgan2222** [comment]
great! Thanks a lot!
