### ISSUE TITLE
Include the option to activate the Quiet Profile without the need to restart the add-on

### ISSUE THREAD

**Issue by dougiteixeira** [adamoutler/HassOSArgonOneAddon#12]
Include the option to activate the Quiet Profile through the home assistant entity without the need to restart the add-on.

Thus, it is possible to define the quiet mode by automation, for example: at night it activates the quiet profile and during the day it is deactivated.

**Comment by adamoutler** [comment]
If you'd like to figure out how to do that, I'd accept a pull request.  I'd like to keep the UI clean.

**Comment by dougiteixeira** [comment]
Ok thanks!  I will study on.
