### ISSUE TITLE
FR: allow manual setting fan speeds per threshold

### ISSUE THREAD

**Issue by Mariusthvdb** [adamoutler/HassOSArgonOneAddon#13]
as far as I understand the add-on (btw thanks for making it!), it can only set a threshold for the fan speed to kick in. If so, I presume it will run the fan at a preset speeds 33%, 66%, 100%. As my experience without the add-on goes, and following discussion on the net about processor temp and processor load, everyones mileage varies a lot....

according to this [video](https://youtu.be/Tgrka088ZFk?t=789) it is possible to set a fanspeed percentage, per threshold. this would allow for even better aligning with real life situations.

Please consider adding that to the add-on?

**Comment by adamoutler** [comment]
Yes you can set arbitrary speeds.  If you'd like to send a pull request, I'd be happy to include it as long as it doesn't increase processing greatly or make the UI messy.  I looked at this and didn't see a way to do it cleanly. 

The nature of this, at the core, is it's fully automatic.  If you did an `i2cset -y 1 0x01a  63` to set the fan to 99%, it would cancel the next temp range change. Someone may complain that the fan isn't doing what they told it to do. 

There are other options where everything is controlled via HA and you would set automations in HA to perform the work.  It is a lot of configuration, but it gives you full control over the fan. 

I offer this workaround:. Set the desired temp range to a wide parameter.  You would be able to use this to set the fan to 0, 1, 3, 33, 66 or 100%.

**Comment by Mariusthvdb** [comment]
Hi, thanks for your response!
I havent set anything yet, I am still in the orientation phase ;-) My Argon case is in the mail, hope it's here by tomorrow....
And in no way be able to create PR, I am no developer unfortunately.

Id be following your instructions, install both add-ons and use the main settings in that. 
So yes, I do support your idea of simple at its core.

what exactly does your workaround need form the user? How can we set these 6 percentages? (I only see 3 options in the config?)

btw, would you know a way to regulate the official Raspberry fan case too (I guess  your add-on wont work with that)

**Comment by adamoutler** [comment]
Quiet Mode will put the fan into 0-1-3-100 steps.  Normal does 0-33-66-100. You can pick where you set it using these items. 

Not sure about the fan case. But you could try my serial/deskpi addon instead of the i2c/argon addon on it. I'll do some research.

**Comment by Mariusthvdb** [comment]
I see, son thats all out of the box as it is right now is it? don't get me wrong, I really love what you did already.

Its just that I also noticed people having different temp thresholds, and especially different real life situations with their Pi's..
so an optional setting for the fanspeeds as the PI seems to offer would make the add-on even more flexible and allow even more tailor made solutions.

but maybe I am overthinking this..

thanks if you could check the fancase, appreciated.

**Comment by adamoutler** [comment]
Raspberry pi case fan uses PWM on GPIO14.  It is incompatible with the other solutions and would need a separate solution.  If you find it important and are willing to test, I could create a solution.

**Comment by Mariusthvdb** [comment]
thats really cool of you. though, maybe no necessary, Ive just received this from @DarrenHill :
https://community.home-assistant.io/t/raspberry-pi-cpu-fan-automation/158239/36?u=mariusthvdb

**Comment by adamoutler** [comment]
That is the solution which depends entirely on Home Assistant.  This solution is self-contained.

**Comment by Mariusthvdb** [comment]
final question here, now that Ive got your add-on running ;-)

can we at all use the [platform: rpi_gpio ](url)https://www.home-assistant.io/integrations/rpi_gpio/ with this? Not sure what we could do there. but since I am exploring new options, maybe we could see the power button, (and its options), or even control it, and of course the fan pin on the GPIO?

**Comment by adamoutler** [comment]
The fan control works via i2c.  It's on a GPIO, but it wiggles differently and much faster. Anything done to control the fan speed would be canceled when the app senses a temp change. 

The power button is unrelated to the operation of this script.  You could use that.

**Comment by Mariusthvdb** [comment]
Powerbutton:
how could we use that? Do you create the entity in the add-on? If not could you accept a FR for that?. Let me close this then, because otherwise things get mixed too much.

**Comment by adamoutler** [comment]
No. I'm not adding power button functionality.
