### ISSUE TITLE
ArgonOne Active Cooling entity do not start automatic if HA starts

### ISSUE THREAD

**Issue by ferropolis** [adamoutler/HassOSArgonOneAddon#15]
Hello, 

ArgonOne Active Cooling entity do not automatic starts if HA starts (Start the add-on at system startup is selected). If you restart HA the entity is not available (see pictuer). Short workaround is to restart the ArgonOne Active Cooling-Add on.  

![2021-07-08 23_31_05-Übersicht - Home Assistant](https://user-images.githubusercontent.com/77990395/124993695-ff445b80-e044-11eb-8155-1413723df42b.png)

protocol
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: ArgonOne Active Cooling
 Actively keeping your Argon One cool.
-----------------------------------------------------------
 Add-on version: 22
 You are running the latest version of this add-on.
 System: Home Assistant OS 6.1  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2021.7.1
 Home Assistant Supervisor: 2021.06.8
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Detecting Layout of i2c, we expect to see "1a" here.
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- 1a -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
Settings initialized. Argon One Detected. Beginning monitor..
Current Temperature 50 °C
Level 1 - Fan 0% (OFF)
Current Temperature 48 °C
Current Temperature 49 °C
Current Temperature 49 °C
Current Temperature 49 °C
```

**Comment by adamoutler** [comment]
The log is showing it has started.   Argon One Active Cooling starts later than most apps.  Refresh that screen and it will show you it is working properly.  There's a bug in HA that prevents proper display when no data is available on boot. It won't try again.

**Comment by viktor-235** [comment]
I have the same issue. Page refreshing doesn't help. Add-on starts according log messages (as written by the author of this issue) but it works only after add-on restarting.
Also, it doesn't control the fan until I restart the add-on.
I've tested it under HA versions 2021.6.6 and 2021.7.1.

**Comment by ferropolis** [comment]
I have try it again and wait 30 min., but same result as my first post: entity do not start automaticly 😔

**Comment by adamoutler** [comment]
I cannot reproduce.

**Comment by adamoutler** [comment]
The fanspeed will now be reported, along with all the attributes every 10 minutes.  New attribute "Temperature F" or "Temperature C" depending on if you are using F'in awesome temp, or not. 
![image](https://user-images.githubusercontent.com/527919/125176773-4d23a580-e1a4-11eb-9f0b-27e77bf1f659.png)
