### ISSUE TITLE
Fan speed % incorrectly showing in HA display

### ISSUE THREAD

**Issue by juancameijeiras** [adamoutler/HassOSArgonOneAddon#19]
Hi! As per your add-on and documentation, there are 4 levels of the fan function: 0-0%-0RPM, LowRange-33%, Medium-66%, and High-100% (max RPM of the fan). In HA history graph, the speed entity of the fan is being reported as % but in reality, what is being piped is the level of the fan (0,1,2,3) so the graph plots 0%, 1%, 2%, 3%. I believe it should be showing 0%, 33%, 66% and 100%.

<img width="386" alt="Screenshot 2021-07-28 at 15 00 00" src="https://user-images.githubusercontent.com/60329458/127326287-4792f66e-d40a-486a-93ef-12703c772748.png">

<img width="1077" alt="Screenshot 2021-07-28 at 15 00 12" src="https://user-images.githubusercontent.com/60329458/127326316-ea95be57-04cf-4ae1-87cb-fb1787901dda.png">

**Comment by adamoutler** [comment]
The graph scales. This picture only shows 1% was attained. They is no history on this sensor because there is no database entry.

**Comment by adamoutler** [comment]
Please verify this is fixed in 24.1

**Comment by kirbo** [comment]
> Please verify this is fixed in 24.1

Seems to work for me, both WITH and WITHOUT QuietProfile
![image](https://user-images.githubusercontent.com/1077974/127736789-69631a9a-1819-4cd9-b9d0-e33d68086433.png)

**Comment by adamoutler** [comment]
Great!

**Comment by adamoutler** [comment]
Thanks @kirbo
