### ISSUE TITLE
Allow ability to configure fan speed percentages

### ISSUE THREAD

**Issue by markgaze** [adamoutler/HassOSArgonOneAddon#2]
For some reason, when I configure the addon to `QuietProfile: true` and the `LowRange` is exceeded, the 1% fan speed sounds awful on my device but the `MediumRange` sounds fine (I've tested this with a few values and anything below 3% lets off a whining noise but everything above that is fine).

It would be nice if I could tell the addon which percentages to use so that I can make use of all three levels, as at the moment I'm using the workaround described below but it would be good if I could set them to be `3%`, `10%` and `100%` or something like that 🙂 

Workaround: I've set the `LowRange` and `MediumRange` to the same value so that it jumps straight to 3%.

Great work though! I just started using the case for HA and finding this addon was ideal! Thanks 😄

**Comment by cgeroldinger** [comment]
Installed today and works great.  Thanks a lot
