### ISSUE TITLE
Not an issue but an improvement proposal

### ISSUE THREAD

**Issue by alberto772** [adamoutler/HassOSArgonOneAddon#21]
I love your works and what you've done.
I've a request for you there is any possibility to add a flag in the configuration tab, to enable the "reboot on power failure".
I see an inconvenient any time that my house lost the power and I'm out for work for a couple of weeks I lost the control because when the power return the argon case don't restore the power state.
the command to enable the always on mode is: i2cset -y 1 0x01a 0xfe (from official docs https://github.com/Argon40Tech/Argon-ONE-i2c-Codes/blob/master/README.md or https://tech.scargill.net/argon-one-case-for-raspberry-pi4/)
the default mode (using the power button) is: i2cset -y 1 0x01a 0xfd
Thanks a lot
Alberto

**Comment by adamoutler** [comment]
No.  We've been down this road before.  The functionality you want only operates on a small subset of V1 devices with upgraded firmware.   The upgrade was on a relatively few number of new devices and there is no way to backport the functionality or flash the new firmware.   V2 devices have a jumper.  You can see previous work in the closed issues.

**Comment by alberto772** [comment]
Hi Adam, thanks to your time and the detailed answer. 
I’ve done a workaround, booting the device with raspbian, issuing the command  i2cset and now it works. Kind regards 
Alberto

**Comment by adamoutler** [comment]
https://github.com/adamoutler/HassOSArgonOneAddon/pull/17
