### ISSUE TITLE
Debian bullseye and HA Supervised - issue

### ISSUE THREAD

**Issue by znanywawa** [adamoutler/HassOSArgonOneAddon#22]
I love using HA and this addon seems to be useful but unfortunately I am experiencing issue:

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: ArgonOne Active Cooling
 Actively keeping your Argon One cool.
-----------------------------------------------------------
 Add-on version: 24.1
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 11 (bullseye)  (armv7 / raspberrypi4)
 Home Assistant Core: 2021.9.6
 Home Assistant Supervisor: 2021.09.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Detecting Layout of i2c, we expect to see "1a" here.
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00: 00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f 
10: 10 11 12 13 14 15 16 17 18 19 1a 1b 1c 1d 1e 1f 
20: 20 21 22 23 24 25 26 27 28 29 2a 2b 2c 2d 2e 2f 
30: -- -- -- -- -- -- -- -- 38 39 3a 3b 3c 3d 3e 3f 
40: 40 41 42 43 44 45 46 47 48 49 4a 4b 4c 4d 4e 4f 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: 60 61 62 63 64 65 66 67 68 69 6a 6b 6c 6d 6e 6f 
70: 70 71 72 73 74 75 76 77 78 79 7a 7b 7c 7d 7e 7f 
Settings initialized. Argon One Detected. Beginning monitor..
Current Temperature 44 °C
2021-09-16_23:56:21: 44C - Level 1 - Fan 0% (OFF)
Error: Write failed
Failed 78: i2cset -y 1 0x01a "${fanPercentHex}"
Error: Write failed
Safe Mode Activated!
Failed 188: return ${returnValue}
Error: Write failed
Safe Mode Activated!
Current Temperature 43 °C
2021-09-16_23:56:51: 43C - Level 1 - Fan 0% (OFF)
Error: Write failed
Failed 78: i2cset -y 1 0x01a "${fanPercentHex}"
Error: Write failed
Safe Mode Activated!
Failed 188: return ${returnValue}
Error: Write failed
Safe Mode Activated!`

ic2 files exists as shou
![image](https://user-images.githubusercontent.com/62244838/137015410-fa3b29ca-d15b-4a54-bf80-6feaca2a2ad5.png)
ld

Other users are having same issues.

Mode details:
Add-on version: 24.1
You are running the latest version of this add-on.
System: Debian GNU/Linux 11 (bullseye) (aarch64 / raspberrypi4-64)
Home Assistant Core: 2021.10.4
Home Assistant Supervisor: 2021.10.0

**Comment by adamoutler** [comment]
It appears that you have about 200 devices on your i2c bus.  There should be just one.  I can't help you sort this out.  I'd recommend talking to the manufacturer and asking for help.  This is beyond me.  When they come up with a solution for your setup, I can look at how to integrate it.
