### ISSUE TITLE
Addon not working with Debian 11 (Bullseye)

### ISSUE THREAD

**Issue by jsrich31** [adamoutler/HassOSArgonOneAddon#23]
I recently updated my PI to Debian 11 to correct and issue with OS no longer being supported. Now that I have moved this Addon no longer functions in the way it was created. 

- Screenshot below shows that fans are off 
- Fans are still running at 100%

-----------------------------------------------------------
 Add-on: ArgonOne Active Cooling
 Actively keeping your Argon One cool.
-----------------------------------------------------------
 Add-on version: 24.1
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 11 (bullseye)  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2021.10.6
 Home Assistant Supervisor: 2021.10.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Detecting Layout of i2c, we expect to see "1a" here.
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00: 00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f 
10: 10 11 12 13 14 15 16 17 18 19 1a 1b 1c 1d 1e 1f 
20: 20 21 22 23 24 25 26 27 28 29 2a 2b 2c 2d 2e 2f 
30: -- -- -- -- -- -- -- -- 38 39 3a 3b 3c 3d 3e 3f 
40: 40 41 42 43 44 45 46 47 48 49 4a 4b 4c 4d 4e 4f 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: 60 61 62 63 64 65 66 67 68 69 6a 6b 6c 6d 6e 6f 
70: 70 71 72 73 74 75 76 77 78 79 7a 7b 7c 7d 7e 7f 
Settings initialized. Argon One Detected. Beginning monitor..
Current Temperature 43 °C
2021-10-20_09:35:29: 43c - Level 1 - Fan 0% (OFF)
Error: Write failed
Failed 78: i2cset -y 1 0x01a "${fanPercentHex}"
Error: Write failed
Safe Mode Activated!
Error: Write failed
Failed 188: return ${returnValue}
Safe Mode Activated!

**Comment by jsrich31** [comment]
Any updates?

**Comment by adamoutler** [comment]
Debian uses a different i2c layout.  I'd rather not clutter the interface with settings.  I will accept a patch if you can find a way to locate the appropriate i2c.  I'd recommend scanning i2c devices with i2c detect until we find one that matches and does not error.  

Previous workarounds are to use the stock fan control and add a fan entity.  

I will accept a patch if you can get this working under debian.

**Comment by adamoutler** [comment]
Please try with Argon One (not linear) V28d
