### ISSUE TITLE
Super irritating issue with Release 2021.12.10

### ISSUE THREAD

**Issue by CyanAutomation** [adamoutler/HassOSArgonOneAddon#27]
I've just upgraded to **Release 2021.12.10**, and suddenly, something in this release causes the control of the ArgonOne fan to go berserk, and I think what's happening is it's cycling to 100% then down to 0% every 2-4 seconds, or something similar. It's making a **Whirrzccrrkkrrkzz** sound on repeat. Doesn't sound healthy; scared my wife.

I disabled the add-on and hard reset (soft reset didn't work) the ArgonOne, and when it came back online the issue stopped, although this also means no more active fan control.

**Comment by adamoutler** [comment]
Sounds like a hardware issue.  When the fan goes to 100% it just makes a louder whooshing sound as anything over 70% is really just noisier.  There should be no c's k's or z's in any sound made by the unit.

**Comment by CyanAutomation** [comment]
Yeah - it’s definitely more than just whooshing. There’s a disconcerting grating sound following every ramp up, then the system realises this and spins the fan down. Then retries; ad nauseam.  

I’m not sure this is a pure hardware failure, as it began IMMEDIATELY after I updated to 2021.12.10. We’ll have to wait to see if other users have the same experience. 

Regards, Marc

**Comment by adamoutler** [comment]
I recommend investigating the issue, invasively.  You may find a problem via visual inspection, or manual turning of the fan.  Also, you may be able to turn the unit on while disassembled to reproduce the problem in a way which is more easily troubleshot. 

I'm not able to reproduce this issue.  Sounds like rubbing, broken blade, imbalanced fan, or other such physical issue.  This addon simply sends a i2c command to a specific address with a command between 0 and 100 in hexadecimal every thirty seconds based on temperature and input parameters.  There's no whirrzccrrkkrrkzz activation command.

**Comment by adamoutler** [comment]
As a non-invasive test, you could install Raspian on an SDCard, then run the Argon script. If the problem persists, the manufacturer may have options for you.

**Comment by CyanAutomation** [comment]
Noted, thanks for the advice. 
Happy for this to be closed, whilst I carry out some separate investigation. 

Regards
Marc Scheimann
