### ISSUE TITLE
Addon not find I2C

### ISSUE THREAD

**Issue by benchristian88** [adamoutler/HassOSArgonOneAddon#28]
Hi

I seem to have the fan running 100% now.  Not sure if it was an update to 2022.3.1 or a hardware issue, but the addon no longer finds my argon one.  its was working fine for the last 6 months.

Any hints on what to do.  I re ran the ic2 plugin and it was happy, so everything is there.

logs---

 Add-on version: 24.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 7.4  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2022.3.1
 Home Assistant Supervisor: 2022.01.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Detecting Layout of i2c, we expect to see "1a" here.
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
Argon One was not detected on i2c. Argon One will show a 1a on the i2c bus above. This add-on will not control temperature without a connection to Argon One.
Current Temperature 48 °C
2022-03-06_16:28:30: 48C - Level 1 - Fan 0% (OFF)
Error: Write failed
Failed 78: i2cset -y 1 0x01a "${fanPercentHex}"
Error: Write failed
Safe Mode Activated!

**Comment by adamoutler** [comment]
Check your hardware.

**Comment by benchristian88** [comment]
sorry, i did a total dismantle to see if the fan was an issue, put it all back together, powered, up and its now working again.  must have been something dislodged I guess.  no idea, but thanks
