### ISSUE TITLE
Addon not working

### ISSUE THREAD

**Issue by pvillanyi** [adamoutler/HassOSArgonOneAddon#29]
HA Core 2022.6.4
Argon One version: 24.1

CPU temp: 71,58 C
When I boot the PI I can hear the fan, but if HA is running I never heard it again... The CPU heat is high...
The switched on Fan Speed entitit doesn't appear...

In the HA Core log: Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:993
Integration: Home Assistant Supervisor ([documentation](https://www.home-assistant.io/integrations/hassio), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+hassio%22))
First occurred: 10:54:36 (8 occurrences)
Last logged: 11:30:15

Could not fetch stats for 7d06b5a0_argon_one_temp: Container addon_7d06b5a0_argon_one_temp is not running

In the ArgonOne log:
Full logs
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: ArgonOne Active Cooling
 Actively keeping your Argon One cool.
-----------------------------------------------------------
 Add-on version: 24.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 8.1  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2022.6.4
 Home Assistant Supervisor: 2022.05.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Cannot find I2C port.  You must enable I2C for this add-on to operate properly
Failed 1: source "$@"
Error: Could not open file `/dev/i2c-1' or `/dev/i2c/1': No such file or directory
Failed 1: source "$@"
Error: Could not open file `/dev/i2c-1' or `/dev/i2c/1': No such file or directory
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

It seams it has problems with I2C, but I have done the steps. I also have removed ArgonOne and reinstalled it...

**Comment by adamoutler** [comment]
You need to enable I2C. I made an add-on to make this even easier. This is in the instructions on the front page of this repository.

**Comment by pvillanyi** [comment]
I See this from the log, but I've made the steps written instructions...

**Comment by adamoutler** [comment]
I2C is not available.  Check your hardware and check that you've rebooted twice after enabling it.

**Comment by pvillanyi** [comment]
I've removed everything and started from the beginning. Now its working...
Thanks for your patience...
