### ISSUE TITLE
Suggestion: timestamp for logs

### ISSUE THREAD

**Issue by somar05** [adamoutler/HassOSArgonOneAddon#3]
First, thanks for you work. You addon was the reason to buy an ArgonOne case. The fan control is very useful.
Just as comment, could be possible include the time stamp for the logs?

Thanks

**Comment by adamoutler** [comment]
Thanks for the suggestion.  I'd like to point out that after initialization, this addon uses pure BASH for all calculations and only calls an external binary for i2c write operations.  This is to keep the footprint and overhead as small as possible.  While other Add-Ons may call python or other external binaries, which in turn load their own dependencies adding to overhead, this one launches /bin/bash and stays there.  This means your fan control runs as efficiently as possible, while adding as little heat as possible to the system, thus keeping your fan utilization to a minimum.

I don't see a good way to get a date from within bash without calling the system `date` binary.  This means every 30 seconds, an external application would need to be loaded and executed.  I think it's probably best to understand that every 30 seconds a new log entry is applied, reviewing the logs would be T-1minute per 2-lines.

**Comment by somar05** [comment]
Understood. Thanks for the explanation.
