### ISSUE TITLE
Addon stoped working - safe mode is actived

### ISSUE THREAD

**Issue by matata86** [adamoutler/HassOSArgonOneAddon#42]
Hi, addon stopped working.

This is log from HassOS I2C Configurator:
crw--w----    1 root     tty         4,  39 Jun  2 20:09 tty39
crw--w----    1 root     tty         4,   4 Jun  2 20:09 tty4
crw--w----    1 root     tty         4,  40 Jun  2 20:09 tty40
crw--w----    1 root     tty         4,  41 Jun  2 20:09 tty41
crw--w----    1 root     tty         4,  42 Jun  2 20:09 tty42
crw--w----    1 root     tty         4,  43 Jun  2 20:09 tty43
crw--w----    1 root     tty         4,  44 Jun  2 20:09 tty44
crw--w----    1 root     tty         4,  45 Jun  2 20:09 tty45
crw--w----    1 root     tty         4,  46 Jun  2 20:09 tty46
crw--w----    1 root     tty         4,  47 Jun  2 20:09 tty47
crw--w----    1 root     tty         4,  48 Jun  2 20:09 tty48
crw--w----    1 root     tty         4,  49 Jun  2 20:09 tty49
crw--w----    1 root     tty         4,   5 Jun  2 20:09 tty5
crw--w----    1 root     tty         4,  50 Jun  2 20:09 tty50
crw--w----    1 root     tty         4,  51 Jun  2 20:09 tty51
crw--w----    1 root     tty         4,  52 Jun  2 20:09 tty52
crw--w----    1 root     tty         4,  53 Jun  2 20:09 tty53
crw--w----    1 root     tty         4,  54 Jun  2 20:09 tty54
crw--w----    1 root     tty         4,  55 Jun  2 20:09 tty55
crw--w----    1 root     tty         4,  56 Jun  2 20:09 tty56
crw--w----    1 root     tty         4,  57 Jun  2 20:09 tty57
crw--w----    1 root     tty         4,  58 Jun  2 20:09 tty58
crw--w----    1 root     tty         4,  59 Jun  2 20:09 tty59
crw--w----    1 root     tty         4,   6 Jun  2 20:09 tty6
crw--w----    1 root     tty         4,  60 Jun  2 20:09 tty60
crw--w----    1 root     tty         4,  61 Jun  2 20:09 tty61
crw--w----    1 root     tty         4,  62 Jun  2 20:09 tty62
crw--w----    1 root     tty         4,  63 Jun  2 20:09 tty63
crw--w----    1 root     tty         4,   7 Jun  2 20:09 tty7
crw--w----    1 root     tty         4,   8 Jun  2 20:09 tty8
crw--w----    1 root     tty         4,   9 Jun  2 20:09 tty9
crw-rw----    1 root     audio     166,   0 Nov  9 07:36 ttyACM0
crw-rw----    1 root     audio     204,  64 Jun  2 20:09 ttyAMA0
crw-------    1 root     root        5,   3 Jun  2 20:09 ttyprintk
crw-------    1 root     root       10, 239 Jun  2 20:09 uhid
crw-------    1 root     root       10, 223 Jun  2 20:09 uinput
crw-rw-rw-    1 root     root        1,   9 Jun  2 20:09 urandom
drwxr-xr-x    2 root     root            60 Jun  2 20:09 usb
drwxr-xr-x    3 root     root            60 Jun  2 20:09 v4l
crw-------    1 root     root      245,   0 Jun  2 20:09 vc-mem
crw-------    1 root     root      239,   0 Jun  2 20:09 vchiq
crw-------    1 root     root       10, 125 Jun  2 20:09 vcio
crw-rw----    1 root     tty         7,   0 Jun  2 20:09 vcs
crw-rw----    1 root     tty         7,   1 Jun  2 20:09 vcs1
crw-rw----    1 root     tty         7,   2 Jun  2 20:09 vcs2
crw-rw----    1 root     tty         7,   3 Jun  2 20:09 vcs3
crw-rw----    1 root     tty         7,   4 Jun  2 20:09 vcs4
crw-rw----    1 root     tty         7,   5 Jun  2 20:09 vcs5
crw-rw----    1 root     tty         7,   6 Jun  2 20:09 vcs6
crw-rw----    1 root     tty         7, 128 Jun  2 20:09 vcsa
crw-rw----    1 root     tty         7, 129 Jun  2 20:09 vcsa1
crw-rw----    1 root     tty         7, 130 Jun  2 20:09 vcsa2
crw-rw----    1 root     tty         7, 131 Jun  2 20:09 vcsa3
crw-rw----    1 root     tty         7, 132 Jun  2 20:09 vcsa4
crw-rw----    1 root     tty         7, 133 Jun  2 20:09 vcsa5
crw-rw----    1 root     tty         7, 134 Jun  2 20:09 vcsa6
crw-rw-rw-    1 root     root       10, 122 Jun  2 20:09 vcsm-cma
crw-rw----    1 root     tty         7,  64 Jun  2 20:09 vcsu
crw-rw----    1 root     tty         7,  65 Jun  2 20:09 vcsu1
crw-rw----    1 root     tty         7,  66 Jun  2 20:09 vcsu2
crw-rw----    1 root     tty         7,  67 Jun  2 20:09 vcsu3
crw-rw----    1 root     tty         7,  68 Jun  2 20:09 vcsu4
crw-rw----    1 root     tty         7,  69 Jun  2 20:09 vcsu5
crw-rw----    1 root     tty         7,  70 Jun  2 20:09 vcsu6
crw-------    1 root     root       10, 127 Jun  2 20:09 vga_arbiter
crw-------    1 root     root       10, 137 Jun  2 20:09 vhci
crw-rw-rw-    1 root     111        10, 238 Jun  2 20:09 vhost-net
crw-rw-rw-    1 root     111        10, 241 Jun  2 20:09 vhost-vsock
crw-rw----    1 root     netdev     81,   5 Jun  2 20:09 video10
crw-rw----    1 root     netdev     81,   6 Jun  2 20:09 video11
crw-rw----    1 root     netdev     81,   9 Jun  2 20:09 video12
crw-rw----    1 root     netdev     81,   0 Jun  2 20:09 video13
crw-rw----    1 root     netdev     81,   1 Jun  2 20:09 video14
crw-rw----    1 root     netdev     81,   2 Jun  2 20:09 video15
crw-rw----    1 root     netdev     81,   3 Jun  2 20:09 video16
crw-rw----    1 root     netdev     81,  11 Jun  2 20:09 video18
crw-rw----    1 root     netdev     81,   7 Jun  2 20:09 video19
crw-rw----    1 root     netdev     81,   4 Jun  2 20:09 video20
crw-rw----    1 root     netdev     81,   8 Jun  2 20:09 video21
crw-rw----    1 root     netdev     81,  10 Jun  2 20:09 video22
crw-rw----    1 root     netdev     81,  13 Jun  2 20:09 video23
crw-rw----    1 root     netdev     81,  12 Jun  2 20:09 video31
crw-------    1 root     root       10, 130 Jun  2 20:09 watchdog
crw-------    1 root     root      247,   0 Jun  2 20:09 watchdog0
crw-rw-rw-    1 root     root        1,   5 Jun  2 20:09 zero
brw-rw----    1 root     disk      254,   0 Jun  2 20:09 zram0
brw-rw----    1 root     disk      254,   1 Jun  2 20:09 zram1
brw-rw----    1 root     disk      254,   2 Jun  2 20:09 zram2
/dev/i2c-1
/dev/i2c-0 /dev/i2c-1 /dev/i2c-10 /dev/i2c-22
Found i2c access!  Nothing to do!  You can remove this add-on.

This is log from ArgonOne Active Linear Cooling:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: ArgonOne Active Linear Cooling
 Actively keeping your Argon One cool.
-----------------------------------------------------------
 Add-on version: 27
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.3  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2022.11.2
 Home Assistant Supervisor: 2022.10.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Detecting Layout of i2c, we expect to see "1a" here.
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
Argon One was not detected on i2c. Argon One will show a 1a on the i2c bus above. This add-on will not control temperature without a connection to Argon One.
Current Temperature = 46 °C
2022-11-09_08:11:05: 46C - Fan 10% | hex:(0xa)
Error: Write failed
Failed 67: i2cset -y 1 0x01a "${fanPercentHex}"
Error: Write failed
Safe Mode Activated!
Failed 133: return ${returnValue}
Error: Write failed
Safe Mode Activated!

**Comment by adamoutler** [comment]
This shows you do not have an i2c connection with an Argon One connected. Troubleshoot your hardware.
