### ISSUE TITLE
Logs say that fan is at 5/10%, but it blows at max speed

### ISSUE THREAD

**Issue by Tsury** [adamoutler/HassOSArgonOneAddon#44]
I recently installed this addon and it seems to only either completely stop the fan or set it to 100%, regardless of the logs. Am I doing something wrong?

I'm using ArgonOne Active Linear Cooling

**Comment by Matan** [comment]
I'm having the same behaviour, the fan is either on or off, nothing in between.

**Comment by adamoutler** [comment]
Which unit do you have?

**Comment by Matan** [comment]
@I've got a v2.6 board with the M.2 extension. I've been digging a bit further, your code is working perfect sending the correct instructions. However, there seems to be an issue with the v2 boards -- https://github.com/Argon40Tech/Argon-ONE-i2c-Codes/issues/7

**Comment by adamoutler** [comment]
Use the Quiet Profile.
