### ISSUE TITLE
Reported upgrade version incorrect

### ISSUE THREAD

**Issue by darylsargent** [adamoutler/HassOSArgonOneAddon#5]
![image](https://user-images.githubusercontent.com/41406374/114389205-10153a80-9bd8-11eb-8443-813c59506aa5.png)

As per the snip - Supervisor reporting version 19 available, currently running version 0.19.  Changelog shows version 0.19 as the latest.

**Comment by adamoutler** [comment]
There's some in-progress workflow changes. I'm attempting to convert over to using pre-made images and troubleshooting errors with the build system.  There will be more non-change-related updates soon.

**Comment by krpn** [comment]
@adamoutler, thank you for this addon. It really usefull. Could you please make stable release and do your tests in testing repo? :) Some people have [updates notifications](https://github.com/krpn/home-assistant-updates-notification) that annoying them with test versions.

**Comment by adamoutler** [comment]
That's what I'm working on.  I don't have much time to work each day. I'm trying to make a system which builds n image and publishes to github.  I'm working on it.
