### ISSUE TITLE
Temperature as an entity instead of an attribute

### ISSUE THREAD

**Issue by spyder007** [adamoutler/HassOSArgonOneAddon#57]
Right now, temperature is recorded as an attribute on the fan.  This limits the availability of that data in dashboards and graphs.  Would we be open to adding an option (Create a Argon Temperature entity in Home Assistant) and report temperature to a separate entity?  I would keep temperature as an attribute on the Fan Speed entity, but adding a new temperature entity would open up some additional visibility (and make it available in Prometheus, which is where my alerting lives :) )

**Comment by spyder007** [comment]
I created a PR for this:  feel free to decline.

**Comment by adamoutler** [comment]
Temperature is best handled other ways.  It was initially considered but the way this project does entities is absolutely the wrong way to do an entity.  Additionally, the sending of the request takes a very long time, relatively speaking. It will tie up a thread on the host machine for about 5 seconds which is another example of doing it wrong, but it uses no external dependencies which is awesome.  

I would say it's better to choose one of the many existing options for RPi temp.  It's way better in my opinion to keep the footprint of this app and it's options to a minimum so as to not introduce bugs, use extra processor, or resources.   This container does one thing really well and provides a report on what it does.

**Comment by spyder007** [comment]
@adamoutler Thanks for the explanation, as I mentioned, I figured it had a 50/50 shot of getting implemented :)
