### ISSUE TITLE
reinstall after update to ver 20

### ISSUE THREAD

**Issue by sky7176** [adamoutler/HassOSArgonOneAddon#6]
Hi,
I have updated the component at last versione 20, all fine.

But after reboot my hass.io server, the component dosen't start automatically, I had configured it to boot at startup.
I had to uninstall and reinstall it.
I didn't see anything in the log.

In any case great job

Giuseppe

**Comment by adamoutler** [comment]
There is a startup queue.  This addon starts some time after home Assistant starts so as to ensure it can create the fan sensor.   It will start but it starts slowly.

**Comment by sky7176** [comment]
Many thanks
