### ISSUE TITLE
Proposal for new implementations

### ISSUE THREAD

**Issue by Jonny-T-cyber** [adamoutler/HassOSArgonOneAddon#68]
Hi,
this is not an issue (indeed congratulations for this addon) but, rather, it is a request for new implementations...
I opened the following topic on the official Argon40 forum:

https://forum.argon40.com/t/argon-one-case-and-raspberry-s-leds/2217

My question is:
Is there the possibility of developing another additional component that can control the two LEDs of the Raspberry with HassOS installed?

Thanks

**Comment by adamoutler** [comment]
Thanks. The LEDs are not controllable via argon One. They would be outside the scope of this addon.  You could look at developing one though.
