### ISSUE TITLE
How to enable i2c, to official documentation does not cover it

### ISSUE THREAD

**Issue by Zzo911** [adamoutler/HassOSArgonOneAddon#70]
Hello,

There is nothing about i2c in the official documentation.
https://www.home-assistant.io/hassio/enable_i2c/
Is it enabled by default now?

Regards

**Comment by buzeeg** [comment]
Hi !

They just moved it to another section : https://www.home-assistant.io/installation/raspberrypi/#enable-i2c
It seems there is 2 methods : one by adding a config file in the boot image, and the other one using the terminal to add the config file.

**Comment by adamoutler** [comment]
Should be fixed in latest version.
