### ISSUE TITLE
i2c enabled, but addon does not work, latest HA 

### ISSUE THREAD

**Issue by zlodei2000** [adamoutler/HassOSArgonOneAddon#73]
i2c addon log:
...
/dev/i2c-1
/dev/i2c-0 /dev/i2c-1 /dev/i2c-10 /dev/i2c-22
Found i2c access!  Nothing to do!  You can remove this add-on.

but Active Linear Cooling addon says:
Detecting Layout of i2c, we expect to see "1a" here.
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
Argon One was not detected on i2c. Argon One will show a 1a on the i2c bus above. This add-on will not control temperature without a connection to Argon One.
Current Temperature = 43 °C
2024-06-04_00:18:07: 43C - Fan 15% | hex:(0xf)
Error: Write failed
Failed 74: i2cset -y 1 0x01a "${fanPercentHex}"
Error: Write failed
Safe Mode Activated!

The error occurred after the latest HA update. Currently I use 
Core 2024.5.5
Supervisor 2024.05.1
Operating System 12.3
Frontend 20240501.1

**Comment by zlodei2000** [comment]
There were no problems with early HA versions (maybe month or two ago, it's difficult to recall exact version)

**Comment by adamoutler** [comment]
That looks like a physical connection issue. There's nothing that can be done from this side.  You'll need to troubleshoot your unit or talk to support.
