### ISSUE TITLE
Fan Speed entity not available in HA after Core Restart

### ISSUE THREAD

**Issue by cargnellogiacomo** [adamoutler/HassOSArgonOneAddon#8]
Hi,

after the restart of the Home Assistant Core, the ArgonOne FAN entity disappears it becomes not available in HomeAssistant. The option "Create a Fan Speed entity in Home Assistant" is of course activated.
Thx

Giacomo

**Comment by adamoutler** [comment]
You must wait for the addon to become active.  It is a different kind of entity without a database entry. It is disabled until it reports in. It also will disable if the fan remains unchanged for hours.
