### ISSUE TITLE
Upgrading to version 20 gives 404 Client Error

### ISSUE THREAD

**Issue by greggotcher** [adamoutler/HassOSArgonOneAddon#9]
I tired to upgrade to version 20 and I have having issues. I am running the lastest Hass version 2021.5.0. When I upgraded I got the following message:

404 Client Error for http+docker://localhost/v1.40/containers/create?name=addon_7d06b5a0_argon_one_temp: Not Found (“No such image: adamoutler/aarch64-hassosargonone:20”)

I rolled back to the snapshot I took before upgrading and everything was good again.

Any help would be greatly appreciated.

**Comment by adamoutler** [comment]
Sounds like a network issue.

**Comment by adamoutler** [comment]
The image is here. https://hub.docker.com/repository/docker/adamoutler/aarch64-hassosargonone
